Add CMake support
ecrc/kblas-gpu pull request #26
Opened 2023-03-11 05:24 UTC by pghysels

We want to use KBLAS in [STRUMPACK](https://github.com/pghysels/STRUMPACK), a CMake build system would make this easier. I'm not a CMake expert but this seems to work for me. 
With the CMake build system it should be easier to create a [spack](https://github.com/spack/spack) install script.

This PR also contains some minor changes for the new MAGMA release.

The FindMAGMA.cmake file was taken from @wavefunction91, I hope that's ok.

2023-03-14 16:26 UTC, ltaiefhatem commented
Dear Pieter,
Thanks for your contribution.
We are looking into it internally and will get back to you soon.
Hatem


From: Pieter Ghysels ***@***.***>
Date: Tuesday, 14 March 2023 at 19:24
To: ecrc/kblas-gpu ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [ecrc/kblas-gpu] Add CMake support (PR #26)

@stefanozampini<https://urldefense.com/v3/__https:/github.com/stefanozampini__;!!Nmw4Hv0!zcwh-YbETWqxDWWj509OT1KlgQvWEwPNPvm9O9AAoPgw2jvryWsSjgm_njZvzGWqFGnnAM11O6_aVPY9B838PJmrDt3hmSs$> @wajihboukaram<https://urldefense.com/v3/__https:/github.com/wajihboukaram__;!!Nmw4Hv0!zcwh-YbETWqxDWWj509OT1KlgQvWEwPNPvm9O9AAoPgw2jvryWsSjgm_njZvzGWqFGnnAM11O6_aVPY9B838PJmrjm_31ps$>

—
Reply to this email directly, view it on GitHub<https://urldefense.com/v3/__https:/github.com/ecrc/kblas-gpu/pull/26*issuecomment-1468422351__;Iw!!Nmw4Hv0!zcwh-YbETWqxDWWj509OT1KlgQvWEwPNPvm9O9AAoPgw2jvryWsSjgm_njZvzGWqFGnnAM11O6_aVPY9B838PJmr1Jjzqoc$>, or unsubscribe<https://urldefense.com/v3/__https:/github.com/notifications/unsubscribe-auth/ABZXIPHMWVI772MU3WLWFR3W4CLTHANCNFSM6AAAAAAVXI4QGY__;!!Nmw4Hv0!zcwh-YbETWqxDWWj509OT1KlgQvWEwPNPvm9O9AAoPgw2jvryWsSjgm_njZvzGWqFGnnAM11O6_aVPY9B838PJmrAGmgeOU$>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

2023-03-14 16:26 UTC, stefanozampini commented on src/batch_triangular/Xgemm_batch_core.cuh
> -                                    (magma_int_t*)m, (magma_int_t*)n, (magma_int_t*)k,
Can you add an ifdef on the magma version to support order versions?

2023-03-14 16:28 UTC, stefanozampini requested changes
Thanks @pghysels

2023-03-14 16:30 UTC, pghysels commented
Thanks, no rush. It might need more testing. I'm not a CMake expert. 
It works for me with:

```
mkdir build
mkdir install
export MAGMA_DIR=/home/pieterg/local/magma-2.7.0/install
cd build
cmake ../ \
      -DCMAKE_INSTALL_PREFIX=../install \
      -DCMAKE_BUILD_TYPE=Debug \
      -DCMAKE_CUDA_COMPILER=/usr/local/cuda-11.7/bin/nvcc \
      -DCMAKE_CXX_COMPILER=g++-11 \
      -DCMAKE_CUDA_ARCHITECTURES="75" \
      -DCMAKE_CUDA_HOST_COMPILER=g++-11 \
      -DBLA_VENDOR=OpenBLAS
make install
```

2023-03-19 21:57 UTC, stefanozampini commented on src/batch_triangular/Xgemm_batch_core.cuh
> -                                    (magma_int_t*)m, (magma_int_t*)n, (magma_int_t*)k,
@pghysels  ping. This would be also useful for PETSc https://gitlab.com/petsc/petsc/-/merge_requests/6206

2023-03-19 21:59 UTC, stefanozampini commented on src/batch_triangular/Xgemm_batch_core.cuh
> -                                    (magma_int_t*)m, (magma_int_t*)n, (magma_int_t*)k,
Sorry, I have missed you already did that. Thanks again, it was on my TODO list

2023-03-20 16:42 UTC, stefanozampini commented
@pghysels we are getting some erros when building with newer magma from PETSc , do you have any idea? /https://gitlab.com/petsc/petsc/-/merge_requests/6206#note_1320816531

2023-03-20 20:50 UTC, stefanozampini commented
@pghysels I will cherry-pick your commits and make another PR

2023-03-27 13:20 UTC, merged